language: C
install: make cmake
compiler:
 - gcc
 - clang
script:
 - cmake -DSANITIZE_ADDRESS=On -DSANITIZE_UNDEFINED=On -DCMAKE_BUILD_TYPE=Debug .
 - make
 - make test
 - gcov CMakeFiles/binson_parser.dir/binson_parser.c.gcno CMakeFiles/binson_writer.dir/binson_writer.c.gcno

after_success:
 - bash <(curl -s https://codecov.io/bash)
